
const router = require('express').Router({ mergeParams: true });
const tenantRoutes = require('../tenant/tenant.routes');
const { requireAuth, requireRole, requireEntityAccess } = require('../../middleware/auth');
const { listEntitiesApi, createEntityApi, updateEntity, changeEntityStatus, deleteEntity, getEntityJiraConfigApi, saveEntityJiraConfigApi, getEffectiveJiraConfigApi, syncEntityJiraMetadataApi, getEntityJiraRequiredFieldsApi, listJiraProjectsApi, listJiraIssueTypesApi } = require('../entities/entity.controller');
const { listUsersApi, createUserApi, getUsersByEntityApi, getUserEntitiesApi } = require('../users/user.controller');
const { listAgentsApi } = require('../agents/agent.controller');
const { createAssignmentApi } = require('../assignments/assignment.controller');
const { listIssuesApi, createIssue, getIssueOrDeny, getIssueApi, updateIssueStatus, assignIssue, triageIssue, updateExecutionMode, createComment, listComments, getTimeline, pushIssueToJira, syncIssueFromJira, getIssueJiraSyncHistory, bulkUpdateIssues } = require('../issues/issue.controller');
const { optionalFiles } = require('../issues/issue.upload');
const fileRoutes = require('../files/file.routes');
const supportGroupRoutes = require('../support-groups/support-group.routes');
const routingRuleRoutes = require('../routing/routing.routes');
const jiraRoutes = require('../integrations/jira/jira.routes');
const { getResolvedJiraFieldMappings, saveJiraFieldMapping, listJiraFieldMappings } = require('../jira-field-mappings/jira-field-mapping.controller');
const { listSlaPoliciesApi, createSlaPolicy, resolveSlaPreviewApi, updateSlaPolicy } = require('../sla/sla.controller');
const { workspaceSummaryApi, workspaceIssuesApi } = require('../agent-workspace/agent-workspace.controller');
const { listSavedViews, createSavedView, updateSavedView, deleteSavedView } = require('../saved-views/saved-view.controller');
const { updateUser } = require('../users/user.controller');
const { listStatusMappingsApi, createStatusMapping, updateStatusMapping } = require('../status-mappings/status-mapping.controller');
const { updateRoutingRule } = require('../routing/routing.controller');
const { adminConsoleSummaryApi } = require('../admin-console/admin-console.controller');
router.use('/tenant', requireAuth, tenantRoutes);
router.get('/entities', requireAuth, listEntitiesApi);
router.post('/entities', requireAuth, createEntityApi);
router.put('/entities/:id', requireAuth, requireRole(['superadmin']), updateEntity);
router.patch('/entities/:id/status', requireAuth, requireRole(['superadmin']), changeEntityStatus);
router.delete('/entities/:id', requireAuth, requireRole(['superadmin']), deleteEntity);
router.get('/entities/:id/users', requireAuth, requireEntityAccess((req) => req.params.id), getUsersByEntityApi);
router.get('/entities/:id/jira-config', requireAuth, requireRole(['superadmin']), getEntityJiraConfigApi);
router.put('/entities/:id/jira-config', requireAuth, requireRole(['superadmin']), saveEntityJiraConfigApi);
router.post('/entities/:id/jira-config/sync-metadata', requireAuth, requireRole(['superadmin']), syncEntityJiraMetadataApi);
router.get('/entities/:id/effective-jira-config', requireAuth, getEffectiveJiraConfigApi);
router.get('/entities/:id/jira-required-fields', requireAuth, getEntityJiraRequiredFieldsApi);
router.get('/users', requireAuth, listUsersApi);
router.post('/users', requireAuth, createUserApi);
router.put('/users/:id', requireAuth, requireRole(['superadmin']), updateUser);
router.get('/users/:id/entities', requireAuth, getUserEntitiesApi);
router.get('/agents', requireAuth, requireRole(['superadmin']), listAgentsApi);
router.post('/assignments/agent', requireAuth, requireRole(['superadmin']), createAssignmentApi);
router.get('/issues', requireAuth, listIssuesApi);
router.post('/issues', requireAuth, optionalFiles('attachments'), createIssue);
router.get('/issues/:id', requireAuth, getIssueOrDeny, getIssueApi);
router.patch('/issues/:id/status', requireAuth, getIssueOrDeny, updateIssueStatus);
router.patch('/issues/:id/assign', requireAuth, getIssueOrDeny, assignIssue);
router.patch('/issues/:id/triage', requireAuth, getIssueOrDeny, triageIssue);
router.patch('/issues/:id/execution', requireAuth, getIssueOrDeny, updateExecutionMode);
router.post('/issues/bulk', requireAuth, bulkUpdateIssues);
router.post('/issues/bulk-update', requireAuth, bulkUpdateIssues);
router.post('/issues/:id/push-to-jira', requireAuth, getIssueOrDeny, pushIssueToJira);
router.post('/issues/:id/sync-from-jira', requireAuth, getIssueOrDeny, syncIssueFromJira);
router.post('/issues/:id/comments', requireAuth, getIssueOrDeny, optionalFiles('attachments'), createComment);
router.get('/issues/:id/comments', requireAuth, getIssueOrDeny, listComments);
router.get('/issues/:id/timeline', requireAuth, getIssueOrDeny, getTimeline);
router.get('/issues/:id/jira-sync-history', requireAuth, getIssueOrDeny, getIssueJiraSyncHistory);
router.get('/agent/workspace/summary', requireAuth, requireRole(['agent', 'superadmin']), workspaceSummaryApi);
router.get('/agent/workspace/issues', requireAuth, requireRole(['agent', 'superadmin']), workspaceIssuesApi);
router.get('/saved-views', requireAuth, requireRole(['agent', 'superadmin']), listSavedViews);
router.post('/saved-views', requireAuth, requireRole(['agent', 'superadmin']), createSavedView);
router.put('/saved-views/:id', requireAuth, requireRole(['agent', 'superadmin']), updateSavedView);
router.delete('/saved-views/:id', requireAuth, requireRole(['agent', 'superadmin']), deleteSavedView);
router.get('/admin/integrations/jira/projects', requireAuth, requireRole(['superadmin']), listJiraProjectsApi);
router.get('/admin/integrations/jira/projects/:projectKey/issue-types', requireAuth, requireRole(['superadmin']), listJiraIssueTypesApi);
router.use('/admin/integrations/jira', requireAuth, requireRole(['superadmin']), jiraRoutes);
router.get('/jira-field-mappings', requireAuth, requireRole(['superadmin']), listJiraFieldMappings);
router.post('/jira-field-mappings', requireAuth, requireRole(['superadmin']), saveJiraFieldMapping);
router.get('/jira-field-mappings/resolved', requireAuth, requireRole(['superadmin']), getResolvedJiraFieldMappings);
router.get('/sla-policies', requireAuth, requireRole(['superadmin']), listSlaPoliciesApi);
router.post('/sla-policies', requireAuth, requireRole(['superadmin']), createSlaPolicy);
router.put('/sla-policies/:id', requireAuth, requireRole(['superadmin']), updateSlaPolicy);
router.get('/sla-policies/resolved', requireAuth, requireRole(['superadmin']), resolveSlaPreviewApi);
router.use('/support-groups', requireAuth, requireRole(['superadmin']), supportGroupRoutes);
router.use('/routing-rules', requireAuth, requireRole(['superadmin']), routingRuleRoutes);
router.put('/routing-rules/:id', requireAuth, requireRole(['superadmin']), updateRoutingRule);
router.get('/admin/console/summary', requireAuth, requireRole(['superadmin']), adminConsoleSummaryApi);
router.get('/status-mappings', requireAuth, requireRole(['superadmin']), listStatusMappingsApi);
router.post('/status-mappings', requireAuth, requireRole(['superadmin']), createStatusMapping);
router.put('/status-mappings/:id', requireAuth, requireRole(['superadmin']), updateStatusMapping);
router.use('/files', requireAuth, fileRoutes);
module.exports = router;
